- .dockerignore
- Dockerfile
- Jenkinsfile
- docker-compose.yml
- Jenkinsfile
- Dockerfile
- .dockerignore
- docker-compose.yml
- Github Webhook
> [#2] 프로젝트 배포 설정, CI/CD 파이프라인 구축

- src/main/resources/application.yml
> [#5] 배포 서버에 SSL/TLS 인증 적용

- src/main/java/bgaebalja/exsherpa/ExsherpaApplication.java
- src/main/java/bgaebalja/exsherpa/MainController.java
- 메인페이지를 렌더링하는 엔드포인트의 RequestMapping 어노테이션을 GetMapping으로 변경
> [#11] 배포 서버에서 메인 페이지 렌더링 엔드포인트를 찾지 못하는 문제 해결

- build.gradle
- jar 빌드 시 src/main/webapp 디렉토리를 포함하도록 수정
> [#11, #16] jar 빌드 시 src/main/webapp 디렉토리를 포함하도록 수정

- Dockerfile
- Jenkinsfile
- build.gradle
- src/main/java/bgaebalja/exsherpa/ExsherpaApplication.java
- src/main/java/bgaebalja/exsherpa/main/MainController.java
- Jenkinsfile
- Dockerfile
- build.gradle
- ExsherpaApplication 클래스
> [#11] 프로젝트 빌드 시 war 파일로 패키징하도록 변경

- Dockerfile
- Jenkinsfile
> [#11, #19] 누락된 jar에서 war로의 변경사항 추가

- src/main/java/bgaebalja/exsherpa/aop/LoggingAspect.java
- src/main/java/bgaebalja/exsherpa/configuration/InterceptorConfig.java
- src/main/java/bgaebalja/exsherpa/interception/LoggingInterceptor.java
- src/main/java/bgaebalja/exsherpa/util/LogConstant.java
- src/main/java/bgaebalja/exsherpa/util/PerformanceMeasurer.java
- src/main/resources/application.yml
- logback-spring.xml
- 애플리케이션 설정 추가
- 전체 Controller Components의 요청과 응답 로깅
- 시간 성능 측정
- 메모리 성능 측정
- 전체 Service Components의 작업 수행 로깅
- 시간 성능 측정
- 메모리 성능 측정
> [#21] 전체 프로젝트의 로깅 프로세스 추가

- src/main/java/bgaebalja/exsherpa/configuration/DataSourceConfig.java
- src/main/java/bgaebalja/exsherpa/configuration/TransactionConfig.java
- src/main/java/bgaebalja/exsherpa/datasource/CustomRoutingDataSource.java
- src/main/java/bgaebalja/exsherpa/datasource/DatabaseType.java
- src/main/resources/logback-spring.xml
- DataSourceConfig
- TransactionConfig
- CustomRoutingDataSource
- DatabaseType
> [#23] 데이터베이스 분산 처리를 위한 라우팅 설정

- src/main/java/bgaebalja/exsherpa/exception/ErrorResponse.java
- src/main/java/bgaebalja/exsherpa/exception/ExceptionMessage.java
- src/main/java/bgaebalja/exsherpa/exception/GlobalExceptionHandler.java
- src/main/java/bgaebalja/exsherpa/exception/IdNoValueException.java
- src/main/java/bgaebalja/exsherpa/exception/InvalidIdException.java
- src/main/java/bgaebalja/exsherpa/exception/InvalidTargetTypeException.java
- src/main/java/bgaebalja/exsherpa/exception/InvalidValueException.java
- src/main/java/bgaebalja/exsherpa/exception/NoValueException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingBooleanException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingFloatException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingIntegerException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingLocalDateTimeException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingLongException.java
- src/main/java/bgaebalja/exsherpa/exception/ParsingShortException.java
- Exception Handler
- 주로 발생하는 공통 예외 처리
- 에러 코드
- 에러 메시지
- 공통 커스텀 예외들
- 공통 커스텀 예외 메시지
> [#27] 공통 예외 처리를 위한 Exception Handler 추가

- src/main/java/bgaebalja/exsherpa/exception/ExceptionMessage.java
- src/main/java/bgaebalja/exsherpa/util/FormatConverter.java
- src/main/java/bgaebalja/exsherpa/util/FormatValidator.java
- src/main/java/bgaebalja/exsherpa/util/RegularExpressionConstant.java
> [#29] 포맷 검증을 위한 FormatValidator 클래스, 포맷 변환을 위한 FormatConverter 클래스 추가

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-cbt.jsp
- ExaminationController 클래스
- user-exam-cbt.jsp
- exam-view.jsp
- main.jsp
> [#31] 메인 페이지에서 CBT기능/유형 연습으로 이동하는 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/exception/InvalidTargetTypeException.java
- src/main/webapp/WEB-INF/views/exam/elementary-practice-view.jsp
- src/main/webapp/WEB-INF/views/exam/middle-high-practice-view.jsp
> [#33] CBT 기능/유형 연습 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/ExamInformationResponse.java
- src/main/java/bgaebalja/exsherpa/exception/InvalidTargetTypeException.java
- src/main/webapp/WEB-INF/views/exam/elementary-practice-view.jsp
- src/main/webapp/WEB-INF/views/exam/middle-high-practice-view.jsp
- src/main/webapp/WEB-INF/views/header.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-cbt.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-notice1.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-notice2.jsp
- ExamInformationResponse 클래스
- user-exam-notice1.jsp
- user-exam-notice2.jsp
- report.jsp
- ExaminationController 클래스
- main.jsp
- user-exam-cbt.jsp
> [#35] 메인 페이지에서 실전시험 1, 실전시험 2, Report 페이지로 이동하는 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/domain/ExamInformationResponse.java
- src/main/webapp/WEB-INF/views/exam/exam-list.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-sound1.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-sound2.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
-  파라미터에 값을 전달할 때도 기본값이 들어 가도록 객체 생성 시 기본값을 추가
> [#42] 사운드 페이지로 이동 시 시험지 ID가 전달되지 않는 문제 해결

- src/main/webapp/WEB-INF/views/main.jsp
> [#44] 메인 페이지 타이틀에 아이콘 추가

- src/main/java/bgaebalja/exsherpa/user/annotation/LoginUserArgumentResolver.java
- src/main/java/bgaebalja/exsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/exsherpa/util/SessionConstant.java
- src/main/webapp/WEB-INF/views/header.jsp
- src/main/webapp/WEB-INF/views/user/login/login.jsp
- 유저 컨트롤러 생성
- 로그인 버튼 클릭시 로그인 화면 매핑
> feat(user): 유저 컨트롤러 생성 및 로그인 버튼 연결

- build.gradle
- src/main/java/bgaebalja/exsherpa/configuration/WebSecurityConfig.java
- src/main/java/bgaebalja/exsherpa/user/dto/UserDTO.java
- src/main/java/bgaebalja/exsherpa/user/repository/UserRepository.java
- src/main/java/bgaebalja/exsherpa/user/service/UserDetailsServiceImpl.java
- src/main/java/bgaebalja/exsherpa/user/service/UserService.java
- src/main/java/bgaebalja/exsherpa/user/service/UserServiceImpl.java
- src/main/webapp/WEB-INF/views/user/login/login.jsp
> feat(user): 시큐리티 추가

- src/main/java/bgaebalja/exsherpa/configuration/WebSecurityConfig.java
- src/main/webapp/WEB-INF/views/header.jsp
> feat(user): 로그인시 로그아웃 버튼 보여주도록 추가

- src/main/java/bgaebalja/exsherpa/configuration/WebSecurityConfig.java
- src/main/java/bgaebalja/exsherpa/user/annotation/LoginUserArgumentResolver.java
- src/main/java/bgaebalja/exsherpa/user/controller/UserController.java
- src/main/webapp/WEB-INF/views/header.jsp
> feat(user): 로그인 및 로그아웃 처리

- src/main/java/bgaebalja/exsherpa/examinationhistory/domain/ExaminationHistory.java
- src/main/java/bgaebalja/exsherpa/examinationhistory/domain/SolvedQuestion.java
- ExaminationHistory 클래스
- SolvedQuestion 클래스
> [#54] 문제풀이 히스토리 엔티티, 푼 문제 엔티티 추가

- src/main/java/bgaebalja/exsherpa/collection/domain/Collection.java
- src/main/java/bgaebalja/exsherpa/exam/domain/GetExamResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetExaminationHistoriesResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetExaminationHistoryResponse.java
- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
- Collection 클래스
- GetExamResponse 클래스
- GetExaminationHistoriesResponse 클래스
- GetExaminationHistoryResponse 클래스
- user-exam-subject.jsp
> [#58] subject 페이지에 실제 데이터베이스에 저장된 시험지와 문제 데이터 적용

- src/main/java/bgaebalja/exsherpa/collection/domain/GetCollectionResponse.java
- src/main/java/bgaebalja/exsherpa/collection/domain/GetCollectionsResponse.java
- src/main/java/bgaebalja/exsherpa/passage/domain/GetPassagesResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionsResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/Question.java
- src/main/java/bgaebalja/exsherpa/util/FormatValidator.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#62] 문제풀이 페이지에 지문과 문제 추가

- src/main/resources/static/googledff038da5859f610.html
> [#64] 구글 서치에 도메인 등록

- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionResponse.java
- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionsResponse.java
- src/main/java/bgaebalja/exsherpa/option/domain/Option.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/Question.java
- src/main/java/bgaebalja/exsherpa/question/domain/QuestionType.java
- Option
- GetOptionsResponse
- GetOptionResponse
> [#66] 문제풀이 페이지에 보기 목록을 받아오는 기능 추가

- src/main/java/bgaebalja/exsherpa/exam/domain/Exam.java
- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionResponse.java
- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionsResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/util/ContentExtractor.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#68] 문제풀이 페이지에 객관식 문제풀이, 주관식 문제풀이 적용

- src/main/java/bgaebalja/exsherpa/util/ContentExtractor.java
> [#68] 문제풀이 페이지로 보내는 시문 데이터에서 <br /> 태그 제거 

- src/main/java/bgaebalja/exsherpa/examination/domain/SolvedQuestion.java
- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionResponse.java
- src/main/java/bgaebalja/exsherpa/option/domain/GetOptionsResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/util/ContentExtractor.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#75] 시험지 저장 시 선택지가 분리되지 않은 문제의 선택지가 존재하지 않는 문제 해결

- src/main/java/bgaebalja/exsherpa/exam/domain/GetExamResponse.java
- src/main/java/bgaebalja/exsherpa/util/FormatConverter.java
- src/main/java/bgaebalja/exsherpa/util/TimeSelector.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#77] 문제 수에 따른 제한 시간 차등 적용

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/ExaminationHistory.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetExaminationHistoryResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionsResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/SolvedQuestion.java
- src/main/java/bgaebalja/exsherpa/examination/repository/ExaminationRepository.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationService.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationServiceImpl.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/question/repository/QuestionRepository.java
- src/main/java/bgaebalja/exsherpa/question/service/QuestionService.java
- src/main/java/bgaebalja/exsherpa/question/service/QuestionServiceImpl.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/service/SolvedQuestionServiceImpl.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- src/main/webapp/WEB-INF/views/item/report-answer.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#84] 기본 리포트 페이지 추가

- build.gradle
> [#84, #85] GSON 의존성 추가 (#84, #85)

- src/main/webapp/WEB-INF/views/item/report-answer.jsp
> [#87] 정답, 해설 페이지의 포맷 변경

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/repository/ExaminationRepository.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationService.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationServiceImpl.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#89] 기본 리포트의 시험지 시퀀스가 제대로 적용되지 않는 문제 해결

- src/main/java/bgaebalja/exsherpa/examination/domain/GetExaminationHistoryResponse.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#91] 상세 리포트 페이지의 평가결과 요약 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionResponse.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#93] 문항 난이도 별 내 성취율 기능 추가

- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- 리터럴로 작성된 이메일 주소를 session의 이메일 주소로 변경
> [#95] 시험 제출 시 타 회원 로그인이 반영되지 않는 문제 해결

- docker-compose.yml
- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/examination/domain/SolvedQuestion.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/exception/ExceptionMessage.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/exception/SolvedQuestionNotFoundException.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/repository/SolvedQuestionRepository.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/service/SolvedQuestionService.java
- src/main/java/bgaebalja/exsherpa/solvedquestion/service/SolvedQuestionServiceImpl.java
- src/main/java/bgaebalja/exsherpa/util/MathComputer.java
- src/main/webapp/WEB-INF/views/item/report-student-answer.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
- 번호
- 교과 영역
- 관련 단원
- 정답 및 해설
- 본인 제출 답안
- 채점 결과
- 시험 응시자 평균 정답률
> [#99] 문항 별 전체 정오표 기능 추가

- src/main/webapp/WEB-INF/views/item/report-student-answer.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#101] 리포트 페이지의 정답과 답안 버튼 디자인 추가

- src/main/resources/application.yml
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- 주관식 답안의 입력 필드가 포함되는 문제의 경우 입력 필드를 추가로 생성하지 않도록 수정
> [#103] 주관식 답안의 입력 필드가 포함되는 문제에도 추가적인 입력 필드가 생성되는 문제 해결

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/util/MathComputer.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#105] 문제 유형 별 전체 정답률, 내 정답률 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/GetSolvedQuestionResponse.java
- src/main/java/bgaebalja/exsherpa/examination/repository/ExaminationRepository.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationService.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationServiceImpl.java
- src/main/java/bgaebalja/exsherpa/util/MathComputer.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#107] 객관식/주관식 별 전체 정답률, 내 정답률 기능 추가

- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
> [#109] 인증되지 않은 사용자가 리포트 페이지로 접근 시 로그인 페이지로 리다이렉트하는 기능 추가

- src/main/java/bgaebalja/exsherpa/exam/domain/GetExamResponse.java
- src/main/java/bgaebalja/exsherpa/question/domain/GetQuestionResponse.java
- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- 주관식 필드 생성 조건 추가
- 주관식의 캐시 로직 분리
> [#113, #114] 주관식 필드 생성 조건 추가, 주관식의 캐시 로직 분리

- src/main/java/bgaebalja/exsherpa/exam/repository/ExamRepository.java
- src/main/java/bgaebalja/exsherpa/exam/service/ExamService.java
- src/main/java/bgaebalja/exsherpa/exam/service/ExamServiceImpl.java
- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/examination/domain/PageInformation.java
- src/main/java/bgaebalja/exsherpa/util/FormatConverter.java
- src/main/java/bgaebalja/exsherpa/util/PageableGenerator.java
- src/main/java/bgaebalja/exsherpa/util/PaginationConstant.java
- src/main/resources/static/googledff038da5859f610.html
- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
- 기출 문제 풀이 페이지네이션
- B셀파 문제 풀이 페이지네이션
> [#120] 시험지 목록 페이지에 페이지네이션 적용

- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#122] 시험지 제출 시 답안을 작성하지 않은 문제가 있으면 해당 문제들의 개수와 번호 목록을 고지하는 기능 추가

- src/main/java/bgaebalja/exsherpa/exam/domain/Exam.java
- src/main/java/bgaebalja/exsherpa/exam/repository/ExamRepository.java
- src/main/java/bgaebalja/exsherpa/exam/service/ExamService.java
- src/main/java/bgaebalja/exsherpa/exam/service/ExamServiceImpl.java
- src/main/java/bgaebalja/exsherpa/examination/controller/ExaminationController.java
- src/main/java/bgaebalja/exsherpa/subject/domain/Subject.java
- src/main/java/bgaebalja/exsherpa/subject/exception/ExceptionMessage.java
- src/main/java/bgaebalja/exsherpa/subject/exception/SubjectNotFoundException.java
- src/main/java/bgaebalja/exsherpa/subject/repository/SubjectRepository.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
- 국어
- 영어
- 수학
- 사회
- 과학
- 역사
- 도덕
> [#124] 기출 문제 목록을 과목 별로 조회하는 방식으로 변경

- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
> [#130] 시험지 제출 시 전송되는 시퀀스 값에 내림차순 기준의 첫 번째 인덱스를 사용하도록 변경

- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#132] 첫 번째 리포트의 점수가 출력되지 않는 문제 해결

- src/main/webapp/WEB-INF/views/exam/exam-view.jsp
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
- 내 성취 수준의 margin-left가 90%까지만 증가하도록 수정
> [#134] 상세 리포트의 내 성취 수준 화살표가 바의 길이를 넘어 가는 문제 해결

- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
-  캐시 데이터가 존재하는 경우 항상 캐시 데이터를 통해 시험 이어하기를 하도록 변경
> [#136] 시험 이어하기의 조건 변경

- src/main/java/bgaebalja/exsherpa/examination/repository/ExaminationRepository.java
- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationServiceImpl.java
> [#140] 리포트 페이지에서 각 시험지의 가장 최신 내역을 불러 오지 못 하는 문제 해결

- src/main/java/bgaebalja/exsherpa/examination/service/ExaminationServiceImpl.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
- src/main/webapp/WEB-INF/views/user/exam/user-exam-subject.jsp
> [#142] 시험 재응시, 이어하기 조건 수정

- src/main/java/bgaebalja/exsherpa/util/MathComputer.java
- src/main/webapp/WEB-INF/views/user/exam/report.jsp
> [#144] 리포트 페이지의 난이도 별 내 정답률 계산 로직 변경

- README.md
- 프로젝트 설명
- 프로젝트 기간
- 관련 URL
- EX셀파 서비스
- EX셀파 CI/CD 파이프라인
- 발표 자료
- 시연 영상
- B개발자팀 노션
- 아키텍처
- ERD
- 사용 기술
> [#146] README.md 추가
